version: '3'

services:
  #PostgreSQL Database for the application
  application-postgres:
    image: "postgres:14.1-alpine"
    container_name: ${DB_SERVER}
    volumes:
      - application-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  #Back-end Spring Boot Application
  application-back:
    build: ./backend
    container_name: ${BACK_END}
    image: ${DOCKER_USERNAME}/${BACK_END}
    environment:
      - DB_SERVER=${DB_SERVER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FRONT_SERVER=${FRONT_END}
    ports:
      - ${BACK_END_PORT}:${BACK_END_PORT}

  application-ui:
    build: ./frontend
    container_name: ${FRONT_END}
    image: ${DOCKER_USERNAME}/${FRONT_END}
    ports:
      - ${FRONT_END_PORT}:80
    links:
      - application-back

#Volumes for DB data
volumes:
  application-data:
    driver: local
